parameters:
#    ac_inst3_event.example.class: AltCloud\Instance3EventBundle\Example

services:
#    ac_inst3_event.example:
#        class: %ac_inst3_event.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
